#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# "bad luck from china" for the 4th iteration
# "bad luck from japan" for the 9th iteration
# "bad luck from italy" for the 17th iteration

count = 0

while [ $count -le 20 ]
do
	echo"$count"
	case $count in
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	(( count++ ))
done
