#!/usr/bin/env bash
# SSH client configuration file

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendENV LANG LC_*
    HashKnownHosts yes
    GSSPAPIAuthentication yes
    GSSPAPIDELEGATECredentials no
